### recuperar todas las peliculas
GET http://localhost:1234/movies

### Recuperar una pelicula por id
GET http://localhost:1234/movies/66830b5fc60589e898e6bf14

### Recuperar todas las peliculas por un genero
GET http://localhost:1234/movies/?genre=action&search=the dark knight

### Crear una pelicula con POST
POST http://localhost:1234/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1975,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://img.fruugo.com/product/4/49/14441494_max.jpg",
    "genre": [
        "Crime",
         "Drama"
         ]
}
### Borrar una pelicula
DELETE http://localhost:1234/movies/66830b5fc60589e898e6bf14

### Actualizar una pelicula
PATCH http://localhost:1234/movies/5ad1a235-0d9c-410a-b32b-220d91689a08
Content-Type: application/json

{
    "title": "Nuevo nombre",
    "year": 1993
}